;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_tool_ui_handler
	.export		_brush_ui_handler
	.import		__current_tool
	.import		_context_container_id
	.import		_create_ui_element
	.import		__draw_ui_element
	.import		__update_ui_element_position
	.import		__draw_ui_box
	.export		_shape_text
	.export		_old_tool

.segment	"DATA"

_shape_text:
	.byte	$53,$48,$41,$50,$45,$00

.segment	"BSS"

_old_tool:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ tool_ui_handler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_tool_ui_handler: near

.segment	"CODE"

	lda     _old_tool
	cmp     __current_tool
	beq     L0004
	lda     __current_tool
	bne     L0004
	jsr     _brush_ui_handler
L0004:	lda     __current_tool
	sta     _old_tool
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ brush_ui_handler (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_brush_ui_handler: near

.segment	"CODE"

	jsr     decsp2
	lda     _context_container_id
	jsr     pusha
	lda     #$05
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #$04
	jsr     pusha
	lda     #$02
	jsr     pusha
	jsr     pusha
	lda     #<(__draw_ui_box)
	ldx     #>(__draw_ui_box)
	jsr     pushax
	ldx     #$00
	txa
	jsr     _create_ui_element
	ldy     #$01
	sta     (sp),y
	lda     _context_container_id
	jsr     __update_ui_element_position
	lda     _context_container_id
	jsr     __draw_ui_element
	jmp     incsp2

.endproc

