;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_create_ui_element
	.export		_init_text_element
	.export		_init_icon_element
	.export		_parse_mouse_input
	.export		_get_keycode
	.export		_check_mouse_over_ui
	.import		__mouse_data
	.export		_keycode
	.import		__ui_type
	.import		__ui_position_x
	.import		__ui_global_pos_x
	.import		__ui_global_pos_y
	.import		__ui_position_y
	.import		__ui_size_x
	.import		__ui_size_y
	.import		__ui_var_1
	.import		__ui_var_2
	.import		__ui_var_3
	.import		__ui_var_4
	.import		__ui_rend_func_low
	.import		__ui_rend_func_high
	.import		__ui_on_mouse
	.import		__ui_parent
	.import		__ui_no_of_children
	.import		__ui_first_child
	.import		__ui_last_child
	.import		__ui_next_sib
	.import		__ui_prev_sib
	.export		_delete_ui_element

.segment	"BSS"

_keycode:
	.res	1,$00

; ---------------------------------------------------------------
; unsigned char __near__ create_ui_element (unsigned char parent_id, unsigned char type, unsigned char pos_x, unsigned char pos_y, unsigned char size_x, unsigned char size_y, unsigned int render_func, unsigned int mouse_func)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_create_ui_element: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp1
	lda     #$01
L0020:	sta     (sp)
	ldx     #$00
	lda     (sp)
	cmp     #$64
	jcs     L0003
	tay
	lda     __ui_type,y
	jne     L0004
	lda     (sp)
	tax
	ldy     #$09
	lda     (sp),y
	sta     __ui_type,x
	lda     (sp)
	tax
	dey
	lda     (sp),y
	sta     __ui_position_x,x
	lda     (sp)
	tax
	dey
	lda     (sp),y
	sta     __ui_position_y,x
	lda     (sp)
	tax
	dey
	lda     (sp),y
	sta     __ui_size_x,x
	lda     (sp)
	tax
	dey
	lda     (sp),y
	sta     __ui_size_y,x
	lda     (sp)
	tax
	ldy     #$03
	lda     (sp),y
	sta     __ui_rend_func_low,x
	lda     #<(__ui_rend_func_high)
	ldx     #>(__ui_rend_func_high)
	clc
	adc     (sp)
	bcc     L000E
	inx
L000E:	sta     ptr1
	stx     ptr1+1
	iny
	lda     (sp),y
	sta     (ptr1)
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L0021
	inx
	clc
L0021:	adc     #<(__ui_on_mouse)
	sta     ptr1
	txa
	adc     #>(__ui_on_mouse)
	sta     ptr1+1
	ldy     #$02
	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
	lda     (sp)
	tay
	lda     #$00
	sta     __ui_prev_sib,y
	lda     (sp)
	tay
	lda     #$00
	sta     __ui_next_sib,y
	lda     (sp)
	tay
	lda     #$00
	sta     __ui_no_of_children,y
	lda     (sp)
	tay
	lda     #$00
	sta     __ui_first_child,y
	lda     (sp)
	tay
	lda     #$00
	sta     __ui_last_child,y
	lda     (sp)
	tax
	ldy     #$0A
	lda     (sp),y
	sta     __ui_parent,x
	lda     (sp),y
	tay
	lda     __ui_last_child,y
	beq     L0015
	ldy     #$0A
	lda     (sp),y
	tay
	lda     __ui_last_child,y
	jsr     pusha
	lda     (sp)
	tax
	ldy     #$01
	lda     (sp),y
	sta     __ui_next_sib,x
	lda     (sp),y
	tax
	lda     (sp)
	sta     __ui_prev_sib,x
	jsr     incsp1
	bra     L001A
L0015:	ldy     #$0A
	lda     (sp),y
	tax
	lda     (sp)
	sta     __ui_first_child,x
	ldy     #$0A
	lda     (sp),y
	tax
	lda     (sp)
	sta     __ui_last_child,x
L001A:	ldy     #$0A
	lda     (sp),y
	tax
	lda     (sp)
	sta     __ui_last_child,x
	lda     #<(__ui_no_of_children)
	ldx     #>(__ui_no_of_children)
	ldy     #$0A
	clc
	adc     (sp),y
	bcc     L001E
	inx
L001E:	sta     sreg
	stx     sreg+1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ina
	sta     (sreg)
	ldx     #$00
	lda     (sp)
	bra     L0003
L0004:	clc
	lda     #$01
	adc     (sp)
	jmp     L0020
L0003:	ldy     #$0B
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ init_text_element (unsigned char ui_id, unsigned int text_ptr)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_text_element: near

.segment	"CODE"

	jsr     pushax
	ldy     #$02
	lda     (sp),y
	tax
	lda     (sp)
	sta     __ui_var_1,x
	lda     #<(__ui_var_2)
	ldx     #>(__ui_var_2)
	ldy     #$02
	clc
	adc     (sp),y
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	dey
	lda     (sp),y
	sta     (ptr1)
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ init_icon_element (unsigned char ui_id, unsigned char icon_addr, unsigned int variable_addr, unsigned char variable_value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_icon_element: near

.segment	"CODE"

	jsr     pusha
	ldy     #$04
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     __ui_var_1,x
	iny
	lda     (sp),y
	tax
	ldy     #$01
	lda     (sp),y
	sta     __ui_var_2,x
	lda     #<(__ui_var_3)
	ldx     #>(__ui_var_3)
	ldy     #$04
	clc
	adc     (sp),y
	bcc     L0004
	inx
L0004:	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (sp),y
	sta     (ptr1)
	ldy     #$04
	lda     (sp),y
	tax
	lda     (sp)
	sta     __ui_var_4,x
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ parse_mouse_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_mouse_input: near

.segment	"CODE"

	lda     __mouse_data
	ldx     __mouse_data+1
	jsr     shrax3
	ina
	jsr     pusha
	lda     __mouse_data+2
	ldx     __mouse_data+2+1
	jsr     shrax3
	ina
	jsr     pusha
	lda     __mouse_data+4
	jsr     pusha
	lda     (sp)
	and     #$01
	beq     L0004
	lda     #$00
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	jsr     _check_mouse_over_ui
	jsr     pusha
	lda     (sp)
	beq     L0005
	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L000C
	inx
	clc
L000C:	adc     #<(__ui_on_mouse)
	tay
	txa
	adc     #>(__ui_on_mouse)
	tax
	tya
	jsr     ldaxi
	cpx     #$00
	bne     L0008
	cmp     #$00
	beq     L0005
L0008:	ldx     #$00
	lda     (sp)
	asl     a
	bcc     L000D
	inx
	clc
L000D:	adc     #<(__ui_on_mouse)
	tay
	txa
	adc     #>(__ui_on_mouse)
	tax
	tya
	jsr     pushw
	jsr     pushw0sp
	ldy     #$04
	ldx     #$00
	lda     (sp),y
	pha
	lda     (sp)
	sta     jmpvec+1
	ldy     #$01
	lda     (sp),y
	sta     jmpvec+2
	pla
	jsr     jmpvec
	jsr     incsp2
	jsr     incsp2
L0005:	jsr     incsp1
L0004:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ get_keycode (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_keycode: near

.segment	"CODE"

	jsr     $FFE4
	sta     _keycode
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ check_mouse_over_ui (unsigned char ui_ind, unsigned char mouse_x, unsigned char mouse_y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_mouse_over_ui: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (sp),y
	tay
	lda     __ui_global_pos_x,y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	tay
	lda     __ui_global_pos_y,y
	jsr     pusha
	ldy     #$04
	lda     (sp),y
	tay
	lda     __ui_size_x,y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	tay
	lda     __ui_size_y,y
	jsr     pusha
	ldy     #$05
	ldx     #$00
	lda     (sp),y
	ldy     #$03
	cmp     (sp),y
	bcc     L001B
	ldy     #$05
	lda     (sp),y
	jsr     pusha0
	ldy     #$03
	lda     (sp),y
	clc
	ldy     #$05
	adc     (sp),y
	bcc     L0019
	inx
L0019:	jsr     tosicmp
	bmi     L0008
	beq     L0008
	ldx     #$00
L001B:	txa
	jmp     incsp7
L0008:	ldy     #$04
	ldx     #$00
	lda     (sp),y
	ldy     #$02
	cmp     (sp),y
	bcc     L001C
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$02
	lda     (sp),y
	clc
	ldy     #$04
	adc     (sp),y
	bcc     L001A
	inx
L001A:	jsr     tosicmp
	bmi     L0020
	beq     L0020
	ldx     #$00
L001C:	txa
	jmp     incsp7
L0020:	ldy     #$06
	lda     (sp),y
	tay
	lda     __ui_first_child,y
	jsr     pusha
	lda     (sp)
	beq     L0013
L0012:	lda     (sp)
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     pusha
	ldy     #$07
	lda     (sp),y
	jsr     _check_mouse_over_ui
	jsr     pusha
	lda     (sp)
	beq     L0015
	ldx     #$00
	lda     (sp)
	jsr     incsp2
	jmp     incsp7
L0015:	ldy     #$01
	lda     (sp),y
	tay
	lda     __ui_next_sib,y
	ldy     #$01
	sta     (sp),y
	lda     (sp),y
	bne     L0017
	ldy     #$08
	tax
	lda     (sp),y
	jsr     incsp2
	jmp     incsp7
L0017:	jsr     incsp1
	bra     L0012
L0013:	ldy     #$07
	tax
	lda     (sp),y
	jsr     incsp1
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ delete_ui_element (unsigned char id)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delete_ui_element: near

.segment	"CODE"

	jsr     pusha
	jmp     incsp1

.endproc

