;
; File generated by cc65 v 2.19 - Git 5c3ff71
;
	.fopt		compiler,"cc65 v 2.19 - Git 5c3ff71"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_get_pressed
	.export		_get_just_pressed
	.export		_old_joystick

.segment	"DATA"

_old_joystick:
	.word	$0000

; ---------------------------------------------------------------
; unsigned char __near__ get_pressed (unsigned int joystick, unsigned int button)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_pressed: near

.segment	"CODE"

	jsr     pushax
	jsr     ldax0sp
	ldy     #$02
	and     (sp),y
	pha
	txa
	iny
	and     (sp),y
	tax
	pla
	cpx     #$00
	bne     L0004
	cmp     #$00
	beq     L0001
L0004:	ldx     #$00
	lda     #$01
L0001:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ get_just_pressed (unsigned int joystick, unsigned int button)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_just_pressed: near

.segment	"CODE"

	jsr     pushax
	jsr     ldax0sp
	ldy     #$02
	and     (sp),y
	pha
	txa
	iny
	and     (sp),y
	tax
	pla
	cpx     #$00
	bne     L0009
	cmp     #$00
	beq     L0001
L0009:	jsr     ldax0sp
	and     _old_joystick
	pha
	txa
	and     _old_joystick+1
	tax
	pla
	cpx     #$00
	bne     L0004
	cmp     #$00
	beq     L000C
L0004:	ldx     #$00
	txa
	jmp     incsp4
L000C:	ina
L0001:	jmp     incsp4

.endproc

